[build]
  publish = "src"
  command = "echo 'sem build necessario, site estatico puro'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[dev]
  command = "npm run dev"
  targetPort = 3000
  publish = "src"